local/dispatch/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "dispatch"

urlpatterns = [
    # path('', views.whole_list, name='whole_list'),
    path('', views.whole_list, name='all_list'),
    path('near_list', views.near_list, name='near_list'),
    path('my_list', views.my_list, name='my_list'),
    path('post/', views.dispatch_post, name='dispatch_post'),
    path('<int:pk>/', views.dispatch_detail, name="dispatch_detail"),

    # path('<int:pk>/comment/', views.comments_create, name='comments_create'),

]

local/lives/urls.py
from django.urls import path
from .views import *


app_name = "lives"

urlpatterns = [
  path('cam/', live_stream, name='live_stream'),
  path('create/', live_create, name='live_create'),
  path('', live_list, name='live_list'),
  path('recent/', live_recent, name='live_recent'),
  path('soon/', live_soon, name='live_soon'),
  path("likes/<int:pk>/", live_likes, name='live_likes'),
  path('detail/<int:pk>', live_detail, name='live_detail'),
]

local/local/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lives/', include('lives.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('travels/', include('travels.urls')),
    path('dispatch/', include('dispatch.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

app_name = "users"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/more-info', views.input_info, name='more_info'),
    path('login/', views.login, name='login'),
    path('id-login', views.id_login, name='id_login' ),
    path('logout/', views.logout, name='logout'),
    path('user/', views.user_view, name='user_list'),
    path('user/follow/<int:id>/<int:pk>/', views.user_follow, name='user_follow'),
    path('mypage/', views.mypage, name='mypage'),
]

local/dispatch/models.py
from django.utils import timezone
from django.db import models
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver

User = get_user_model()

# Create your models here.
class Dispatch(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 작성자
    city = models.CharField(max_length=50)
    country  = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    photo = models.ImageField(upload_to='dispatch_photos/', blank=True, null=True)

class Comment(models.Model):
    article = models.ForeignKey(Dispatch, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)  # 작성자
    content = models.TextField()  # 댓글 내용
    created_date = models.DateTimeField(auto_now_add=True)  # 작성일
    def __str__(self):
        return self.content

local/dispatch/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content':'댓글내용',
        }
        # fields = '__all__'
        # exclude = ('article', 'user',)

local/dispatch/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import CommentForm
from django.views.decorators.http import require_POST
from django.utils import timezone
# Create your views here.
def whole_list(request):
    dispatchs = Dispatch.objects.all()
    return render(request, 'dispatch/dispatch_all.html', {'dispatchs':dispatchs})

def near_list(request):
    return render(request, 'dispatch/dispatch_near.html', {})

@login_required
def my_list(request):
    my_dispatchs = Dispatch.objects.filter(username=request.user)
    return render(request, 'dispatch/my.html', {'my_dispatchs': my_dispatchs})

# def dispatch_detail(request, pk):
#     print(pk)
#     dispatchs = get_object_or_404(dispatch, id=pk)
#     return render(request, 'dispatch/dispatch_detail.html', {'dispatchs':dispatchs})

@login_required
def dispatch_post(request):
    if request.method == 'POST':
        dispatch_post = Dispatch.objects.create(
        content=request.POST.get('content'),
        country=request.POST.get('country'),
        city=request.POST.get('city'),
        photo = request.FILES.get('photo'),
        author=request.user
        )
    
        return redirect('dispatch:all_list')
    
    return render(request, 'dispatch/dispatch_post.html')


def dispatch_detail(request, pk):
    dispatch_obj = Dispatch.objects.get(pk=pk)
    comments = Comment.objects.filter(article=dispatch_obj)
    # dispatch_obj = get_object_or_404(dispatch, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.article = dispatch_obj
            comment.save()
            return redirect('dispatch:dispatch_detail', pk=dispatch_obj.pk)
            # return redirect('dispatch:whole_list')
            # return render(request, 'dispatch/dispatch_detail.html')
            # return redirect('dispatch/dispatch_detail.html',pk=dispatch.pk )
    else:
        form = CommentForm()
    context = {
        'dispatch_obj': dispatch_obj,
        'comments': comments,
        'form': form
    }
    return render(request, 'dispatch/dispatch_detail.html', context)
# @require_POST
# def comments_create(request, pk):
#     if request.user.is_authenticated:
#         dispatch_obj = get_object_or_404(dispatch, pk=pk)
#         comment_form = CommentForm(request.POST)
#         if comment_form.is_valid():
#             comment = comment_form.save(commit=False)
#             comment.article = dispatch_obj
#             comment.user = request.user
#             comment.save()
#         return render(request, 'dispatch/dispatch_detail.html', {dispatch_obj.pk})
#     else:
#         form = CommentForm()
#
#     context = {'form': form}
#     return render(request, 'dispatch/comment_form.html', context)


    # if request.user.is_authenticated:
    #     article = get_object_or_404(dispatch, pk=pk)
    #     comment_form = CommentForm(request.POST)
    #     if comment_form.is_valid():
    #         comment = comment_form.save(commit=False)
    #         comment.article = article
    #         comment.user = request.user
    #         comment.save()
    #     return redirect('dispatch:whole_list', article.pk)
    # return redirect('dispatch:my_list')

def comments_delete(request, dispatch_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('dispatch:whole_list', dispatch_pk)

local/dispatch/templates/dispatch/comment_form.html
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">{% csrf_token %}
<!--        {{ form.as_p }}-->
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control"name="content" id="content"
                      rows="3">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary" formaction="{% url 'dispatch:dispatch_detail' dispatch_obj.pk %}">저장하기</button>
    </form>
</div>
{% endblock %}

local/dispatch/templates/dispatch/dispatch_all.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/base2.css' %}" />
        <style>
            a {
                text-decoration: none;
                color: black;
            }
        </style>
        <script>
            // HTML이 로드된 후 실행되는 함수
            window.onload = function() {
                var dispatchTimes = document.getElementsByClassName("dispatch-time");
                for (var i = 0; i < dispatchTimes.length; i++) {
                    var createdAt = dispatchTimes[i].textContent;
                    var parsedTime = moment(createdAt, "YYYY-MM-DDTHH:mm:ssZ").fromNow();
                    dispatchTimes[i].textContent = parsedTime;
                }
            };
        </script>
    </head>
    <body>
        <div class="top">
            <img src="{% static 'logo.svg' %}" />
            <img src="{% static 'alert.svg' %}" />
            <img src="{% static 'ticket.svg' %}" />
            <b style="color: #ff552b">3개</b>
        </div>

        <div>
            <ul class="menu1">
                <li>
                    <a href="{% url 'dispatch:all_list' %}"><b>전체</b></a>
                </li>
                <li>
                    <a href="{% url 'dispatch:near_list' %}">여기 근처</a>
                </li>
                <li>
                    <a href="{% url 'dispatch:my_list' %}">내 파견</a>
                </li>
            </ul>
        </div>

        <div class="prof">

            <div style="display: flex; flex-direction: row">
                <div style="width: 40px; height: 40px">
                    <img
                        style="width: 40px; height: 40px; border-radius: 100%"
                        src="{% static 'profile.svg' %}"
                        style="border-radius: 10px"
                    />
                </div>
                {% for dispatch in dispatchs %}
                <div style="margin-left: 5px">
                    <b>{{ dispatch.author }}</b><br />{{ dispatch.city }}, {{
                    dispatch.country }}
                </div>
            </div>
            <p class="box5">
                <a
                    href="{% url 'dispatch:dispatch_detail' pk=dispatch.pk %}"
                    style="text-decoration: none; color: black"
                    >{{ dispatch.content }}</a
                >
            </p>
            <span class="dispatch-time"
                >{{ dispatch.created_at|date:'Y-m-dTH:i:s' }}</span
            >
            <p>답변 {{ dispatch.comment_set.count }}개 · 나도 궁금해요 12</p>
            <hr />
            <div class="share">
                <b>저장하기</b>
                <b
                    ><a
                        href="{% url 'dispatch:dispatch_detail' pk=dispatch.pk %}"
                        >댓글쓰기</a
                    >
                </b>
                <b><button onclick="">?나도궁금</button></b>

            </div>
            <hr />
            {% endfor %}
            <!---->

            <div class="prof">
                <div style="display: flex; flex-direction: row">
                    <div style="width: 40px; height: 40px">
                        <img
                            style="
                                width: 40px;
                                height: 40px;
                                border-radius: 100%;
                            "
                            src="{% static 'profile.svg' %}"
                        />
                    </div>
                    <div style="margin-left: 5px">
                        {% for comment in dispatch.comment_set.all %} {{
                        comment.author }}리얼로컬<br />
                    </div>
                </div>
            </div>

            <span style="margin-left: 50px">{{ comment.content }}</span>
            {% empty %} {% endfor %}

            <!--        <b id="diff" name="diff">다른 답변 보기</b>-->
            <!--        <div class="empty"></div>-->
            <!---->
            <a href="{% url 'dispatch:dispatch_post' %}"
                ><img src="{% static 'plus.svg' %}" id="plus"
            /></a>
            <footer>
                <div class="footer">
                    <ul class="foot">
                        <li>
                            <a href=""
                                ><img src="{% static 'Group 4.svg' %}"
                            /></a>
                        </li>
                        <li>
                            <a href=""
                                ><img src="{% static 'Group 3on.svg' %}"
                            /></a>
                        </li>
                        <li><img src="{% static 'Group 2.svg' %}" /></li>
                        <li><img src="{% static 'Group 511.svg' %}" /></li>
                    </ul>
                </div>
            </footer>
            <script src="{% static 'js/moreComments.js' %}"></script>
            <
        </div>

    </body>
</html>

local/dispatch/templates/dispatch/dispatch_my.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/base2.css' %}" />
        <style>
            a {
                text-decoration: none;
                color: black;
            }
            .logout {
                position: absolute;
                top: 23px;
                right: 10px;
            }
        </style>
    </head>
    <body>
        <div class="top">
            <img src="{% static 'logo.svg' %}" />
            <div style="float: right; height: 30px">
                <img src="{% static 'alert.svg' %}" />
                <img
                    src="{% static 'ticket.svg' %}"
                    style="margin-right: 20px"
                />
                <b class="logout" style="color: #ff552b">3개</b>
            </div>
            <b
                style="
                    float: right;
                    text-decoration: underline;
                    color: gray;
                    font-size: 7pt;
                "
            >
                {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}">로그아웃</a>
                {% else %}
                <a href="{% url 'users:login' %}">로그인</a>
                {% endif %}
            </b>
        </div>
        <div>
            <ul class="menu1">
                <li>
                    <a href="{% url 'dispatch:all_list' %}"><b>전체</b></a>
                </li>
                <li>
                    <a href="{% url 'dispatch:near_list' %}">여기 근처</a>
                </li>
                <li>
                    <a href="{% url 'dispatch:my_list' %}">내 파견</a>
                </li>
            </ul>
        </div>
        <!---->

        <div class="prof">
            <div
                style="
                    width: 40px;
                    height: 40px;
                    border: 1px solid;
                    border-radius: 100%;
                "
            ></div>
            <div style="margin-left: 5px"><b>닉네임</b><br />삿포로, 일본</div>
        </div>
        <p class="box5">
            지금 삿포로 시내 스스키노 거리 부근이 다 공사 중이라는데 맞나요?
            숙소를 그 근처에 잡았는데 소음이 심할까봐 걱정됩니다.. 그 근처에
            계시는 분 아무나 알려주세요!
        </p>
        <p>1시간 전</p>
        <p>답변 2개 · 나도 궁금해요 12</p>
        <hr />
        <div class="share">
            <b>저장하기</b> <b>댓글 쓰기</b> <b>공유하기</b>
        </div>
        <hr />
        <!---->
        <div class="prof">
            <div
                style="
                    width: 30px;
                    height: 30px;
                    border: 1px solid;
                    border-radius: 100%;
                "
            ></div>
            <div style="margin-left: 5px">
                <b>닉네임</b>리얼로컬<br />스스키노 1번가 쪽만 공사 중이고 다른
                곳은 괜찮아요~
            </div>
        </div>
        <b id="diff" name="diff">다른 답변 보기</b>
        <div class="empty"></div>
        <hr />
        <div class="prof">
            <div
                style="
                    width: 40px;
                    height: 40px;
                    border: 1px solid;
                    border-radius: 100%;
                "
            ></div>
            <div style="margin-left: 5px"><b>닉네임</b><br />삿포로, 일본</div>
        </div>
        <p class="box5">
            지금 삿포로 시내 스스키노 거리 부근이 다 공사 중이라는데 맞나요?
            숙소를 그 근처에 잡았는데 소음이 심할까봐 걱정됩니다.. 그 근처에
            계시는 분 아무나 알려주세요!
        </p>
        <p>1시간 전</p>
        <p>답변 2개 · 나도 궁금해요 12</p>
        <hr />
        <div class="share">
            <b>저장하기</b> <b>댓글 쓰기</b> <b>공유하기</b>
        </div>
        <hr />
        <!---->
        <div class="prof">
            <div
                style="
                    width: 30px;
                    height: 30px;
                    border: 1px solid;
                    border-radius: 100%;
                "
            ></div>
            <div style="margin-left: 5px">
                <b>닉네임</b>리얼로컬<br />스스키노 1번가 쪽만 공사 중이고 다른
                곳은 괜찮아요~
            </div>
        </div>
        <b id="diff" name="diff">다른 답변 보기</b>
        <div id="empty"></div>

        <a href=""><img src="{% static 'plus.svg' %}" id="plus" /></a>
        <footer>
            <div class="footer">
                <ul class="foot">
                    <li>
                        <a href=""><img src="{% static 'Group 4.svg' %}" /></a>
                    </li>
                    <li>
                        <a href=""
                            ><img src="{% static 'Group 3on.svg' %}"
                        /></a>
                    </li>
                    <li><img src="{% static 'Group 2.svg' %}" /></li>
                    <li><img src="{% static 'Group 511.svg' %}" /></li>
                </ul>
            </div>
        </footer>
        <script src="{% static 'js/moreComments.js' %}"></script>
    </body>
</html>

local/dispatch/templates/dispatch/dispatch_near.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/base2.css' %}" />

        <style>
            .city {
                width: 90%;
                background-color: lightgray;
                border: 0.5px;
                border-radius: 10px;
            }

            a {
                text-decoration: none;
                color: black;
            }
            .logout {
                position: absolute;
                top: 23px;
                right: 10px;
            }
        </style>
    </head>
    <body>
        <div class="top">
            <img src="{% static 'logo.svg' %}" />
            <div style="float: right; height: 30px">
                <img src="{% static 'alert.svg' %}" />
                <img
                    src="{% static 'ticket.svg' %}"
                    style="margin-right: 20px"
                />
                <b class="logout" style="color: #ff552b">3개</b>
            </div>
            <b
                style="
                    float: right;
                    text-decoration: underline;
                    color: gray;
                    font-size: 7pt;
                "
            >
                {% if user.is_authenticated %}
                <a href="{% url 'users:logout' %}">로그아웃</a>
                {% else %}
                <a href="{% url 'users:login' %}">로그인</a>
                {% endif %}
            </b>
        </div>
        <div>
            <ul class="menu1">
                <li>
                    <a href="{% url 'dispatch:all_list' %}"><b>전체</b></a>
                </li>
                <li>
                    <a href="{% url 'dispatch:near_list' %}">여기 근처</a>
                </li>
                <li>
                    <a href="{% url 'dispatch:my_list' %}">내 파견</a>
                </li>
            </ul>
        </div>
        <form>
            {% csrf_token %}
            <input type="search" class="city" />
            <input type="submit" value="&#128269;" />
        </form>
        <br /><br />
        <div class="prof">
            <div
                style="
                    width: 40px;
                    height: 40px;
                    border: 1px solid;
                    border-radius: 100%;
                "
            ></div>
            <div style="margin-left: 5px"><b>닉네임</b><br />삿포로, 일본</div>
        </div>
        <p class="box5">
            지금 삿포로 시내 스스키노 거리 부근이 다 공사 중이라는데 맞나요?
            숙소를 그 근처에 잡았는데 소음이 심할까봐 걱정됩니다.. 그 근처에
            계시는 분 아무나 알려주세요!
        </p>
        <p>1시간 전</p>
        <p>답변 2개 · 나도 궁금해요 12</p>
        <hr />
        <div class="share">
            <b>저장하기</b> <b>댓글 쓰기</b> <b>공유하기</b>
        </div>
        <hr />
        <!---->
        <div class="prof">
            <div
                style="
                    width: 30px;
                    height: 30px;
                    border: 1px solid;
                    border-radius: 100%;
                "
            ></div>
            <div style="margin-left: 5px">
                <b>닉네임</b>리얼로컬<br />
                <div>스스키노 1번가 쪽만 공사 중이고 다른 곳은 괜찮아요~</div>
            </div>
        </div>
        <b id="diff" name="diff">다른 답변 보기</b>
        <div class="empty"></div>
        <hr />
        <div class="prof">
            <div
                style="
                    width: 40px;
                    height: 40px;
                    border: 1px solid;
                    border-radius: 100%;
                "
            ></div>
            <div style="margin-left: 5px"><b>닉네임</b><br />삿포로, 일본</div>
        </div>
        <p class="box5">
            지금 삿포로 시내 스스키노 거리 부근이 다 공사 중이라는데 맞나요?
            숙소를 그 근처에 잡았는데 소음이 심할까봐 걱정됩니다.. 그 근처에
            계시는 분 아무나 알려주세요!
        </p>
        <p>1시간 전</p>
        <p>답변 2개 · 나도 궁금해요 12</p>
        <hr />
        <div class="share">
            <b>저장하기</b> <b>댓글 쓰기</b> <b>공유하기</b>
        </div>
        <hr />
        <!---->
        <div class="prof">
            <div
                style="
                    width: 30px;
                    height: 30px;
                    border: 1px solid;
                    border-radius: 100%;
                "
            ></div>
            <div style="margin-left: 5px">
                <b>닉네임</b>리얼로컬<br />스스키노 1번가 쪽만 공사 중이고 다른
                곳은 괜찮아요~
            </div>
        </div>
        <b id="diff" name="diff">다른 답변 보기</b>
        <div id="empty"></div>
        <a href=""><img src="{% static 'plus.svg' %}" id="plus" /></a>
        <footer>
            <div class="footer">
                <ul class="foot">
                    <li>
                        <a href=""><img src="{% static 'Group 4.svg' %}" /></a>
                    </li>
                    <li>
                        <a href=""
                            ><img src="{% static 'Group 3on.svg' %}"
                        /></a>
                    </li>
                    <li><img src="{% static 'Group 2.svg' %}" /></li>
                    <li><img src="{% static 'Group 511.svg' %}" /></li>
                </ul>
            </div>
        </footer>
        <script src="{% static 'js/moreComments.js' %}"></script>
    </body>
</html>

local/dispatch/templates/dispatch/my.html
<html>
    <head>
        <title>local 목록 앱</title>
        <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    </head>
    <body>
        <div class="container">
            <h1>내 파견 페이지 입니다</h1>

            <br>
            <br>
            <a href="{% url 'dispatch:whole_list' %}">전체</a>
            &nbsp
            <a href="{% url 'dispatch:near_list' %}">여기 근처</a>
            &nbsp
            <a href="{% url 'dispatch:my_list' %}">내 파견</a>
            <br>
            <br>
<!--            <a href="{% url 'dispatch:dispatch_post' %}">파견 추가</a>-->
            <p>
            <a href="{% url 'dispatch:dispatch_post' %}"><i class="bi-plus"></i>파견 추가</a>
            </p>
            <ul class="list-group">

            <li class="list-group-item">
                {% for dispatch_obj in my_dispatchs %}
                <p>{{ dispatch_obj.username }}</p>
                <p>{{ dispatch_obj.city }}, {{ dispatch_obj.country }}</p>
                <a href="{% url 'dispatch:dispatch_detail' pk=dispatch_obj.pk %}">{{ dispatch_obj.content }}</a>
                <br>
                <br>
                {{ dispatch_obj.created_at }}
                <hr>
                {% for comment in dispatch_obj.comment_set.all %}
                <div>
                    <strong>{{ comment.author }}</strong>
                    <p>{{ comment.content }}</p>
                </div>
                {% empty %}
                <p>작성한 댓글이 없습니다.</p>
                {% endfor %}
                {% empty %}
                <p>작성한 dispatch가 없습니다.</p>
                {% endfor %}
            </li>

            </ul>
        </div>
    </body>
</html>

local/dispatch/templates/dispatch/near.html
<html>
    <head>
        <title>local 목록 앱</title>
        <link
        rel="stylesheet"
        href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    </head>
    <body>
        <div class="container">
            <h1>여기근처 페이지 입니다@</h1>

            <br>
            <br>
            <a href="{% url 'dispatch:whole_list' %}">전체</a>
            &nbsp
            <a href="{% url 'dispatch:near_list' %}">여기 근처</a>
            &nbsp
            <a href="{% url 'dispatch:my_list' %}">내 파견</a>
            <br>
            <br>
<!--            <a href="{% url 'dispatch:dispatch_post' %}">파견 추가</a>-->
            <p>
            <a href="{% url 'dispatch:dispatch_post' %}"><i class="bi-plus"></i>파견 추가</a>

            </p>
            <ul class="list-group">
            {% for dispatch in dispatchs %}
            <li class="list-group-item">
                {{ dispatch.username }}
                {{ dispatch.city }}
                {{ dispatch.country}}
                <br>

                <a href="{% url 'dispatch:dispatch_detail' pk=dispatch.pk %}">{{ dispatch.content}}</a>
                <br>
                <br>
                {{ dispatch.created_at }}

            </li>
            {% endfor %}
            </ul>
        </div>
    </body>
</html>

local/dispatch/templates/dispatch/whole.html
<html>
<head>
    <title>local 앱</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script>
        // HTML이 로드된 후 실행되는 함수
        window.onload = function() {
            var dispatchTimes = document.getElementsByClassName("dispatch-time");
            for (var i = 0; i < dispatchTimes.length; i++) {
                var createdAt = dispatchTimes[i].textContent;
                var parsedTime = moment(createdAt, "YYYY-MM-DDTHH:mm:ssZ").fromNow();
                dispatchTimes[i].textContent = parsedTime;
            }
        };

        // 카카오톡 공유
        function shareKakao(url, text) {
            var encodedUrl = encodeURIComponent(url);
            var encodedText = encodeURIComponent(text);
            window.open("https://story.kakao.com/share?url=" + encodedUrl + "&text=" + encodedText);
        }
    </script>
</head>
<body>
    <div class="container">
        <h1>전체 페이지 입니다@</h1>
        유저이름 : {{user.username}}
        <br>
        <br>
    <a href="{% url 'dispatch:whole_list' %}">전체</a>
        &nbsp
        <a href="{% url 'dispatch:near_list' %}">여기 근처</a>
        &nbsp
        <a href="{% url 'dispatch:my_list' %}">내 파견</a>
        <br>
        <br>
        <p>
            <a href="{% url 'dispatch:dispatch_post' %}"><i class="bi-plus"></i>파견 추가</a>
        </p>
        <ul class="list-group">
            {% for dispatch in dispatchs %}
            <li class="list-group-item">
                {{ dispatch.author.profile.nickname }}
<!--                {{ request.user.profile.nickname }}-->
                {{ dispatch.city }}
                {{ dispatch.country }}
                <br>
                <a href="{% url 'dispatch:dispatch_detail' pk=dispatch.pk %}">{{ dispatch.content }}</a>
                <br>
                <br>
                <span class="dispatch-time">{{ dispatch.created_at|date:'Y-m-dTH:i:s' }}</span>
                <br>
                <br>
                답변 {{ dispatch.comment_set.count }}개
                <br>
                저장하기
                &nbsp
                <a href="{% url 'dispatch:dispatch_detail' pk=dispatch.pk %}">댓글쓰기</a>
                &nbsp
                <button onclick="shareKakao('{{ request.scheme }}://{{ request.get_host }}{% url 'dispatch:dispatch_detail' pk=dispatch.pk %}', '{{ dispatch.content }}')">공유하기</button>
                <hr>
                {% for comment in dispatch.comment_set.all %}
                <div>
                    <strong>{{ comment.author }}</strong>
                    <p>{{ comment.content }}</p>
                </div>
                {% empty %}
                <p></p>
                {% endfor %}
            </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>