local/dispatch/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "dispatch"

urlpatterns = [
    # path('', views.whole_list, name='whole_list'),
    path('', views.whole_list, name='all_list'),
    path('near_list', views.near_list, name='near_list'),
    path('my_list', views.my_list, name='my_list'),
    path('post/', views.dispatch_post, name='dispatch_post'),
    path('<int:pk>/', views.dispatch_detail, name="dispatch_detail"),

    # path('<int:pk>/comment/', views.comments_create, name='comments_create'),

]

local/lives/urls.py
from django.urls import path
from .views import *


app_name = "lives"

urlpatterns = [
  path('cam/', live_stream, name='live_stream'),
  path('create/', live_create, name='live_create'),
  path('', live_list, name='live_list'),
  path('recent/', live_recent, name='live_recent'),
  path('soon/', live_soon, name='live_soon'),
  path("likes/<int:pk>/", live_likes, name='live_likes'),
  path('detail/<int:pk>', live_detail, name='live_detail'),
]

local/local/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lives/', include('lives.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('travels/', include('travels.urls')),
    path('dispatch/', include('dispatch.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local/travels/urls.py
from django.urls import path
from .views import *

app_name = "travels"

urlpatterns = [
  path('', travel_list, name='travel_list'),
  path('<int:pk>/', travel_detail, name='travel_detail'),
  path("likes/<int:pk>/", travel_likes, name='travel_likes'),
  path('create/', travel_create, name='travel_creaet'),
  # path('delete/<int:pk>/', travel_delete, name='travel_delete'),
]

local/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

app_name = "users"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/more-info', views.input_info, name='more_info'),
    path('login/', views.login, name='login'),
    path('id-login', views.id_login, name='id_login' ),
    path('logout/', views.logout, name='logout'),
    path('user/', views.user_view, name='user_list'),
    path('user/follow/<int:id>/<int:pk>/', views.user_follow, name='user_follow'),
    path('mypage/', views.mypage, name='mypage'),
]

local/travels/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class TravelPost(models.Model):
  title = models.CharField(max_length=30)
  content = models.TextField()
  nation = models.TextField()
  city = models.TextField()
  together = models.IntegerField(default=1)
  start_date = models.DateTimeField()
  end_date = models.DateTimeField()
  create_date = models.DateTimeField(auto_now_add=True)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  views = models.IntegerField(default=0)
  likes = models.ManyToManyField(User, related_name='TravelLikes', blank=True)

  def __str__(self):
    return self.title
  
class TravelPhoto(models.Model):
  travel = models.ForeignKey(TravelPost, on_delete=models.CASCADE, null=True, blank=True)
  image = models.ImageField(upload_to='travels/', blank=True, null=True)
  
  
class TravelComment(models.Model):
  travel = models.ForeignKey(TravelPost, on_delete=models.CASCADE)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  content = models.TextField()
  create_date = models.DateTimeField(auto_now_add=True)

local/travels/forms.py
from django import forms
from .models import TravelComment

class TravelCommentForm(forms.ModelForm):
  content = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': '댓글을 입력해주세요'})
    )
  content.label = '' 
  class Meta:
    model = TravelComment
    fields = ('content',)
    labels = {'content': ''}

local/travels/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .models import *
from .forms import TravelCommentForm
from users.models import Profile


# Create your views here.
def travel_list(request):
  travels = TravelPost.objects.all()
  query = request.GET.get('query')
  if query:
    travels = TravelPost.objects.filter(nation__icontains=query) | TravelPost.objects.filter(city__icontains=query)
  context = {
    'travels' : travels,
    'query': query,
  }
  return render(request, 'travels/travel_list.html', context)


def travel_detail(request, pk):
  travel = TravelPost.objects.get(pk=pk)
  comments = TravelComment.objects.filter(travel=pk)
  travel.views += 1 
  travel.save()
  
  writer_user = travel.author

  if request.method == 'POST':
    form = TravelCommentForm(request.POST)
    if form.is_valid():
      comment = form.save(commit=False)
      comment.travel = travel
      comment.author = request.user
      comment.save()
      return redirect('travels:travel_detail',travel.pk) 
    
  else:
    form = TravelCommentForm()
    user_list = Profile.objects.exclude(user=request.user).prefetch_related('followers', 'followings')
    context = {
    'travel' : travel,
    'comments' : comments,
    'form' : form,
    'user_list':user_list,
    'current_user': request.user,
    'writer_user' : writer_user
    } 
  return render(request, 'travels/travel_detail.html', context)

@login_required
def travel_create(request):
  if request.method == 'POST':
    travel_post = TravelPost.objects.create(
      title=request.POST.get('title'),
      content=request.POST.get('content'),
      nation=request.POST.get('nation'),
      city=request.POST.get('city'),
      together=int(request.POST.get('together')),
      start_date=request.POST.get('start_date'),
      end_date=request.POST.get('end_date'),
      author=request.user
    )
    
    image_files = request.FILES.getlist('image_files')
    for image_file in image_files:
      TravelPhoto.objects.create(travel=travel_post, image=image_file)
    return redirect('travels:travel_list')
  
  return render(request, 'travels/travel_create.html')

# def travel_delete(request, pk):
#   if request.method == "POST":
#     travel = get_object_or_404(TravelPost, pk=pk)
#     travel.delete()
#   return redirect('travels:travel_list')

@require_POST
def travel_likes(request, pk, *args, **kwargs):
  if request.user.is_authenticated:
    travel = get_object_or_404(TravelPost, pk=pk)
    users = travel.likes.all()
    if users.filter(pk=request.user.pk).exists():
      travel.likes.remove(request.user)
    else:
      travel.likes.add(request.user)
    return redirect('travels:travel_detail',pk)
  return render(request, 'travels/travel_detail.html')

local/travels/templates/travels/travel_create.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/travel_create.css'%}"/>
    </head>
    <body>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="top-bar">
                <button type="button" id="close-button" onclick="location.href='onboarding.html'"><img src="{% static 'img/close-button.png' %}" alt="닫기"></button>
                <span id="txt-post">여행포스트 작성하기</span>
                <button type="submit"id="post-btn" >등록</button>
            </div>

            <div class="box">
                <div class="txt">국가</div>
                <input type="text" name="nation" placeholder="포스트를 작성할 국가명을 입력해 주세요." id="txt-box"/>
                <div class="sub-txt">예 : 대한민국, 일본, 태국, 미국, 대만</div>
            </div>
            <div class="box">
                <div class="txt">도시</div>
                <input type="text" name="city" placeholder="위의 국가에서 포스트를 작성할 도시명을 입력해 주세요." id="txt-box" />
                <div class="sub-txt">예 : 서울, 강릉, 제주, 나고야, 삿포로, 하노이, 파리, 로마, 뉴욕, 라스베가스</div>
            </div>
            <div class="box">
                <div class="txt">여행 일자</div>
                <div class="box-flex">
                <div class="start">
                    <div class="sub-txt">시작일</div>
                    <input type="date" required name="start_date" data-placeholder="날짜 선택" id="start-date"/>
                </div>
                <div style="padding-top: 30px; color: #A7A5A5;">~</div>
                <div class="end">
                    <div class="sub-txt" style="margin-left: 15px;">종료일</div>
                    <input type="date" required name="end_date" data-placeholder="날짜 선택" id="end-date"/>
                </div>
                </div>
            </div>
            <div class="box">
                <div class="txt">여행 인원</div>
                <div class="box-flex">
                    <input type="number" name="together" value="1" id="together" placeholder="숫자"/>
                    <div class="sub-txt" style="margin-top: 15px; margin-left: 5px;">인</div>
                </div>
            </div>
            <img src="{% static 'img/divide-line.svg'%}" id="line">
            <input type="text" name="title" placeholder="제목을 입력하세요" id="title"/>
            <img src="{% static 'img/divide-line-thin.svg'%}" id="thin-line">
            <textarea name="content" placeholder="내용을 입력해주세요." id="content"></textarea>
            <input type="file" name="image_files" multiple id="file"/>
        </form>
    </body>
</html>

local/travels/templates/travels/travel_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/travel_detail.css' %}"/>
    </head>
    <body>
        <a href="{% url 'travels:travel_list' %}"><img src="../../static/img/back.svg" alt="닫기" id="back"></button></a>
        <div class="slider">
            {% for photo in travel.travelphoto_set.all %}
                <img src="{{ photo.image.url }}" alt="Travel Photo" class="img-size">
            {% empty %}
            <img src="{% static 'img/slide1.jpg' %}" id="img1">
            {% endfor %}
        </div>
        {% if user.is_authenticated %}
        <form action="{% url 'travels:travel_likes' travel.pk %}" method="POST">
            {% csrf_token %} 
            {% if user in travel.likes.all %}
            <button type="submit" id="bm_btn"><img src="../../static/img/yes-bm.svg"></button>
            {% else %}
            <button type="submit" id="bm_btn"><img src="../../static/img/bookmark.svg"></button>
            {% endif %}
        </form>
        {% endif %} 

        <div class="where">{{travel.nation}}, {{travel.city}} | </div><div class="who"> 거의 로컬</div>

        <div class="title">{{travel.title}}</div>

        <div id="profile">
            <div class="box">
                <img class="profile" src="../../static/img/slide2.jpg" alt="프사">
            </div>
            <div class="info">
                <div class="nickname">{{travel.author.profile.nickname}}</div>
                <div class="when">{{travel.create_date|date:"m/d"}}</div>
            </div>
            
                {% if current_user in writer_user.profile.followers.all %}
                    <a href="{% url 'users:user_follow' writer_user.id travel.pk %}"><button type="button" id="follow-btn">- 언팔로우</button></a>
                {% else %}
                    <a href="{% url 'users:user_follow' writer_user.id travel.pk %}"><button type="button" id="follow-btn">+ 팔로우</button></a>
                {% endif %}
            


        </div>

        <div class="travel-info">
            <div class="flex">
            <div class="date">여행일자 <span id="highlight">{{ travel.start_date|date:"d.m.y" }} - {{ travel.end_date|date:"d.m.y" }}</span></div>
            <div class="personnel">여행인원 <span id="highlight">{{travel.together}}인</span></div>
        </div>        
        <div class="post-content">
            {{travel.content}}
        </div>
        </div>
        <hr style="border:10px solid #FBFBFC;">
        <div class="comment-here">
        {% for comment in travel.travelcomment_set.all %}
        <div id="profile">
            <div class="comment-box">
                <img class="profile" src="../../static/img/slide3.jpg" alt="댓글프사">

                {% comment %} {% if comment.author.profile.profile_photo.url %}
                <img class="profile" src="{{comment.author.profile.profile_photo.url}}" alt="댓글프사">
                {% else %}
                <img class="profile" src="../../static/img/slide3.jpg" alt="댓글프사">
                {% endif %} {% endcomment %}
            </div>
            <div class="info">
                {% if comment.author.profile.nickname %}
                <div class="comment-nickname">{{comment.author.profile.nickname}}</div>
                {% else %}
                <div class="comment-nickname">비공개</div>
                {% endif %}
                <div class="comment">{{comment.content}}</div>
            </div>
        </div>
        <div class="like-recomment">
            <button type="button" id="like-btn"><img src="../../static/img/like-btn.svg"> 좋아요</button>
            <button type="button" id="recomment-btn">• 답글달기</button>
        </div>
        {% empty %}
        가장 먼저 댓글을 작성해보세요 
        {% endfor %}
        {% if user.is_authenticated %}
        <div class="write-box">
        <form method="post" id = "comment-form">
            {% csrf_token %} 
            {{form.as_p}}
            <button type="submit" value="작성 완료" id="write-btn">작성</button>
        </form>
        </div>  
        {% else %}
        <input type="text" name="content" placeholder="댓글을 작성하려면 로그인을 해주세요" disabled>
        {% endif %}
    
    </body>
</html>

local/travels/templates/travels/travel_list.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/travel_list.css' %}">
  <title>Local</title>
</head>
<body>
  <div id="mpage-main">
    <div id="logo-bar" class="p-1">
      <img src="{% static 'img/logo.svg' %}" alt="">
      <div class="flex align-center">
        <a href=""><img src="{% static 'img/alert.svg' %}" alt=""></a>
        {% if user.is_authenticated %}
        <p class="flex align-center"><img src="{% static 'img/ticket.svg' %}" alt="">3개</p>
        {% endif %}
      </div>
    </div>
    <nav id="mpage-nav" class="p-1">
      <a href="">로컬여행</a>
    </nav>
    <div id="t-searchbox">
      <form action="{% url 'travels:travel_list' %}">
        {% if query %}
        <input type="text" name="query" value="{{query}}" placeholder="위치를 입력하세요.">
        {% else %}
        <input type="text" name="query" placeholder="위치를 입력하세요.">
        {% endif %}
        <button type="submit">검색</button>
      </form>
    </div>
    <div>
      {% if travels %}
      <small class="p-1">전체 {{travels.count}}개</small>
      {% endif %}
      {% for travel in travels %}
      <div class="t-list-box">
        <a href="{% url 'travels:travel_detail' travel.pk %}">
        {% with photo=travel.travelphoto_set.first %}
        {% if photo %}
          <img src="{{ photo.image.url }}" alt="여행 사진" id="travel_img">
        {% else %}
          <img src="{% static 'img/ticket.svg' %}" alt="아무 랜덤사진?" id="travel_img">
        {% endif %}
        {% endwith %}
          <h3>{{travel.title}}</h3>
          <p class="t-box-user flex align-center">
            {% if travel.author.profile.nickname %}
            <img src="{{ travel.author.profile.profile_photo }} " alt="">
            {% else %}
            <img src="{% static 'img/profile.svg' %}" alt="">
            {% endif %}
            {% if travel.author.profile.nickname %}
            {{ travel.author.profile.nickname }} 
            {% else %}
            {{travel.author.profile.nickname}}
            {% endif %}
            | 거의 로컬
          </p>
          <p>{{travel.likes.count}}명 북마크 | {{travel.views}}명 조회</p>
        </a>
      </div>
      {% empty %}
      <div id="nullbox">
        <p>검색 결과가 없습니다.</p>
      </div>
      {% endfor %}
    </div>
  <footer>
    <ul class="foot">
      <li>
        <a href="{% url 'lives:live_list' %}">
          <img src="{% static 'img/lolive.svg' %}"/>
        </a>
      </li>
      <li>
        <a href="{% url 'dispatch:all_list' %}"><img src="{% static 'img/Group 3.svg' %}" /></a>
      </li>
      <li>
        <a href="{% url 'travels:travel_list' %}"><img src="{% static 'img/lotravel.svg' %}" /></a>
      </li>

      <li>
        {% if user.is_authenticated %}
        <a href="{% url 'users:mypage' %}">
          <img src="{% static 'img/Group 511.svg' %}" />
        </a>
        {% else %}
        <a href="{% url 'users:login' %}">
          <img src="{% static 'img/Group 511.svg' %}" />
        </a>
        {% endif %}
      </li>
    </ul>
  </footer>
</body>
</html>