local/dispatch/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "dispatch"

urlpatterns = [
    # path('', views.whole_list, name='whole_list'),
    path('', views.whole_list, name='all_list'),
    path('near_list', views.near_list, name='near_list'),
    path('my_list', views.my_list, name='my_list'),
    path('post/', views.dispatch_post, name='dispatch_post'),
    path('<int:pk>/', views.dispatch_detail, name="dispatch_detail"),

    # path('<int:pk>/comment/', views.comments_create, name='comments_create'),

]

local/lives/urls.py
from django.urls import path
from .views import *


app_name = "lives"

urlpatterns = [
  path('cam/', live_stream, name='live_stream'),
  path('create/', live_create, name='live_create'),
  path('', live_list, name='live_list'),
  path('recent/', live_recent, name='live_recent'),
  path('soon/', live_soon, name='live_soon'),
  path("likes/<int:pk>/", live_likes, name='live_likes'),
  path('detail/<int:pk>', live_detail, name='live_detail'),
]

local/local/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lives/', include('lives.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('travels/', include('travels.urls')),
    path('dispatch/', include('dispatch.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local/travels/urls.py
from django.urls import path
from .views import *

app_name = "travels"

urlpatterns = [
  path('', travel_list, name='travel_list'),
  path('<int:pk>/', travel_detail, name='travel_detail'),
  path("likes/<int:pk>/", travel_likes, name='travel_likes'),
  path('create/', travel_create, name='travel_creaet'),
  # path('delete/<int:pk>/', travel_delete, name='travel_delete'),
]

local/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

app_name = "users"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/more-info', views.input_info, name='more_info'),
    path('login/', views.login, name='login'),
    path('id-login', views.id_login, name='id_login' ),
    path('logout/', views.logout, name='logout'),
    path('user/', views.user_view, name='user_list'),
    path('user/follow/<int:id>/<int:pk>/', views.user_follow, name='user_follow'),
    path('mypage/', views.mypage, name='mypage'),
]

local/lives/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Video(models.Model):
  STATE_CHOICES = [
    ('ongoing', '지금 라이브 중'),
    ('reservation', '방송 예정'),
    ('finished', '방송 종료'),
  ]
  state = models.CharField(max_length=20, choices=STATE_CHOICES)
  title = models.CharField(max_length=30)
  sub1 = models.CharField(max_length=30)
  sub2 = models.CharField(max_length=30)
  sub3 = models.CharField(max_length=30)
  video_file = models.FileField(upload_to='lives/')
  thumbnail = models.ImageField(upload_to='lives/thumbnail/')
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  nation = models.TextField()
  city = models.TextField()
  views = models.IntegerField(default=0)
  date = models.DateTimeField()
  saves = models.ManyToManyField(User, related_name='Livelikes', blank=True)
  alarms = models.BooleanField(default=False)

  def __str__(self):
    return self.title
  
  
class VideoComment(models.Model):
  video = models.ForeignKey(Video, on_delete=models.CASCADE)
  author = models.ForeignKey(User, on_delete=models.CASCADE)
  content = models.TextField()
  create_date = models.DateTimeField(auto_now_add=True)

local/lives/forms.py
from django import forms
from .models import VideoComment

class VideoCommentForm(forms.ModelForm):
  content = forms.CharField(widget=forms.TextInput)
  content.label = '' 
  class Meta:
    model = VideoComment
    fields = ('content',)
    labels = {'content': ''}

local/lives/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import *
from django.core.mail import EmailMessage
from django.views.decorators import gzip
from django.http import StreamingHttpResponse
import cv2
import threading
from .forms import VideoCommentForm
from django.contrib.auth.decorators import login_required

from django.views.decorators.http import require_POST

from users.models import Profile



# class VideoStreamingView(View):
#   def get(self, request, *args, **kwargs):
#     channel_layer = get_channel_layer()
#     async_to_sync(channel_layer.group_send)("video_stream", {"type": "stream.video"})
#     return HttpResponse("Video streaming started.")



@gzip.gzip_page
def live_stream(request):
  try:
    cam = VideoCamera()
    return StreamingHttpResponse(gen(cam), content_type="multipart/x-mixed-replace;boundary=frame")
  except:
    pass
  return render(request, 'lives/live_stream.html')

#to capture video class
class VideoCamera(object):
  def __init__(self):
    self.video = cv2.VideoCapture(0)
    (self.grabbed, self.frame) = self.video.read()
    threading.Thread(target=self.update, args=()).start()

  def __del__(self):
    self.video.release()

  def get_frame(self):
    image = self.frame
    _, jpeg = cv2.imencode('.jpg', image)
    return jpeg.tobytes()

  def update(self):
    while True:
      (self.grabbed, self.frame) = self.video.read()

def gen(camera):
  while True:
    frame = camera.get_frame()

    yield (b'--fram\r\n'
            b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
    

# def home(request):
#     yield (b'--frame\r\n'
#       b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

#     if request.user.is_authenticated:  # 로그인된 상태인지 확인
#         try:
#             profile = request.user.profile  # 프로필 객체 가져오기
#         except Profile.DoesNotExist:
#             # 프로필 객체가 없는 경우 신규 프로필 생성
#             profile = Profile.objects.create(user=request.user)

#         if not profile.phone:  # phone 필드가 비어있는지 확인
#             return redirect('users:more_info')
#     else:
#         return render(request, 'lives:live_list')

#     return render(request, 'lives:live_list')


    

def live_list(request):
  video = Video.objects.all()[:6]
  osaka1 = None
  osakas = None

  try:
    osaka1 = Video.objects.filter(city__icontains='오사카').latest('id')
  except Video.DoesNotExist:
    pass

  try:
    osakas = Video.objects.filter(city__icontains='오사카').order_by('-id')[1:4]
  except Video.DoesNotExist:
    pass

  query = request.GET.get('query')
  if query:
    travels = Video.objects.filter(nation__icontains=query) | Video.objects.filter(city__icontains=query)

  context = {
    'video': video,
    'query': query,
    'osaka1': osaka1,
    'osakas': osakas,
  }

  if request.user.is_authenticated:  # 로그인된 상태인지 확인
    try:
        profile = request.user.profile  # 프로필 객체 가져오기
    except Profile.DoesNotExist:
        # 프로필 객체가 없는 경우 신규 프로필 생성
        profile = Profile.objects.create(user=request.user)

    if not profile.phone:  # phone 필드가 비어있는지 확인
      return redirect('users:more_info')
  else:
      return render(request, 'lives/live_home.html', context)

  return render(request, 'lives/live_home.html', context)

def live_recent(request):
  video = Video.objects.all().order_by('-id')
  query = request.GET.get('query')
  if query:
    video = Video.objects.filter(nation__icontains=query) | Video.objects.filter(city__icontains=query)
  context = {
    'video': video,
    'query': query,
  }
  return render(request, 'lives/live_recent.html', context)

def live_soon(request):
  video = Video.objects.filter(state='reservation')
  context = {
    'video': video,
  }
  return render(request, 'lives/live_soon.html', context)


def live_detail(request, pk):
  video = Video.objects.get(pk=pk)
  comments = VideoComment.objects.filter(video=pk)
  if request.method == 'POST':
    form = VideoCommentForm(request.POST)
    if form.is_valid():
      comment = form.save(commit=False)
      comment.video = video
      comment.author = request.user
      comment.save()
      return redirect('lives:live_detail',video.pk) 
    
  else:
    form = VideoCommentForm()
  context = {
    'video' : video,
    'comments' : comments,
    'form' : form
  } 
  return render(request, 'lives/live_detail.html', context)

@login_required
def live_create(request):
  if request.method == 'POST':
    # POST 요청을 처리하여 새로운 Video 객체 생성
    state = request.POST.get('state')
    title = request.POST.get('title')
    sub1 = request.POST.get('sub1')
    sub2 = request.POST.get('sub2')
    sub3 = request.POST.get('sub3')
    video_file = request.FILES.get('video_file')
    thumbnail = request.FILES.get('thumbnail')
    author = request.user 
    nation = request.POST.get('nation')
    city = request.POST.get('city')
    views = 0 
    date = request.POST.get('date')
    
    video = Video.objects.create(
      state=state,
      title=title,
      sub1=sub1,
      sub2=sub2,
      sub3=sub3,
      video_file=video_file,
      thumbnail=thumbnail,
      author=author,
      nation=nation,
      city=city,
      views=views,
      date=date
    )
    # 새로운 Video 객체 생성 후, 어떤 작업을 수행하거나 리디렉션할 수 있음
    
    return redirect('lives:live_detail', video_id=video.id)
  # GET 요청 처리
  return render(request, 'lives/live_create.html')


@require_POST
def live_likes(request, pk, *args, **kwargs):
  if request.user.is_authenticated:
    video = get_object_or_404(Video, pk=pk)
    users = video.saves.all()
    if users.filter(pk=request.user.pk).exists():
      video.saves.remove(request.user)
    else:
      video.saves.add(request.user)
    return redirect('lives:live_detail',pk)
  return render(request, 'lives/live_detail.html')

local/lives/templates/lives/live_Soon.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/soon.css' %}" />
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <style>
            .logout:link a:visited {
                text-decoration: none;
                color: gray;
            }
        </style>
    </head>
    <body>
        <div class="top">
            <img src="{% static 'logo.svg' %}" />
            {% if user.is_authenticated %}
            <div style="float: right; height: 30px">
                <img src="{% static 'alert.svg' %}" />
                <img
                    src="{% static 'ticket.svg' %}"
                    style="margin-right: 20px"
                />
                <b class="logout" style="color: #ff552b">3개</b>
            </div>
            {% endif %}
            <b
                style="
                    float: right;
                    text-decoration: underline;
                    color: gray;
                    font-size: 7pt;
                "
            >
                {% if user.is_authenticated %}

                <a href="{% url 'users:logout' %}">로그아웃</a>
                {% else %}
                <a href="{% url 'users:login' %}">로그인</a>
                {% endif %}
            </b>
        </div>
        <div>
            <ul class="menu1">
                <li>
                    <a href="{% url 'lives:live_list' %}">홈</a>
                </li>
                <li>
                    <a href="{% url 'lives:live_recent' %}">최신 방송순</a>
                </li>
                <li>
                    <a href="{% url 'lives:live_soon' %}"><b>라이브 예고</b></a>
                </li>
            </ul>
        </div>

        <p><b>라이브 예고</b></p>
        {% for video in video %}
        <div class="box4">
            <div class="blank">
                {{ video.date|date:"m월d일" }}<br />
                {{ video.date|time:"H:i" }}
            </div>
            <section class="later">
                <b style="font-size: 12pt">{{ video.title }}</b>
                <br /><b style="font-size: 10pt; color: #ff552b"
                    >{{ video.nation }}, {{ video.city }}</b
                ><br />
                <b style="font-size: 7pt">닉네임</b><br />
                <ul class="list1">
                    <li>{{video.sub1}}</li>
                    <li>{{video.sub2}}</li>
                    <li>{{video.sub3}}</li>
                </ul>
                <button id="button">
                    <div class="btn">
                        <img src="{% static 'alert.svg' %}" />
                        <b>알림 받기</b>
                    </div>
                </button>
            </section>
        </div>
        <br />
        {% empty %} 예정된 라이브가 없습니다. {% endfor %}

        <footer>
            <div class="footer">
                <ul class="foot">
                    <li>
                        <a href="{% url 'lives:live_list' %}"
                            ><img src="{% static 'Group 4on.svg' %}"
                        /></a>
                    </li>
                    <li>
                        <a href="{% url 'dispatch:all_list' %}"><img src="{% static 'Group 3.svg' %}" /></a>
                    </li>
                    <li>
                        <a href="{% url 'travels:travel_list' %}"><img src="{% static 'Group 2.svg' %}" /></a>
                    </li>
                    <li>
                        <a href="{% url 'users:login' %}">
                            <img src="{% static 'Group 511.svg' %}" />
                        </a>
                    </li>
                </ul>
            </div>
        </footer>
        <script>
            var button = document.getElementById("button");
            button.addEventListener("click", function () {
                alert("선택하신 라이브에 대한 알림 받기가 설정되었습니다.");
            });
        </script>
    </body>
</html>

local/lives/templates/lives/live_create.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <!-- create_video.html -->
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <label for="state">상태:</label>
    <select name="state" id="state">
      <option value="ongoing">지금 라이브 중</option>
      <option value="reservation">방송 예정</option>
      <option value="finished">방송 종료</option>
    </select>
    <br>
    <input type="text" name="title">
    <input type="text" name="sub1">
    <input type="text" name="sub2">
    <input type="text" name="sub3">
    <input type="file" name="video_file">
    <input type="file" name="thumbnail">

    <br>
    <input type="text" name="nation">
    <input type="text" name="city">
    <input type="datetime-local" name="date">

    <input type="submit">
  </form>

</body>
</html>

local/lives/templates/lives/live_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <style>
            .box9 {
                padding: 3px;
                overflow-y: scroll;
            }
            .submitbox {
                display: flex;
                justify-content: center;
                color: #ff552b;
                background-color: white;
                border-radius: 10px;
                height: 25px;
                width: 60px;
            }
            #live-box {
                width:3rem;
                height:3rem;
                border-radius: 2rem
            }
        </style>
    </head>
    <body>
        <div style="width: 100%; height: 60%">
            <video
                controls
                autoplay
                style="width: 100%; height: 100%; padding: 0"
            >
                <source src="{{ video.video_file.url }}" type="video/mp4" />
            </video>
        </div>
        <p>
            <a href=""><img src="{% static 'Union.svg' %}" /></a>
        </p>
        <br />
        <div class="box9">
            {% for comment in video.videocomment_set.all %}
            <div>
                <div style="display: flex; align-items: center">
                    {% if video.author.profile.profile_photo %}
                    <img
                        src="{{video.author.profile.profile_photo.url}}"
                        style="width: 30px; height: 30px"
                    />
                    {% else %}
                    <img
                        src="{% static 'profile.svg' %}"
                        style="width: 30px; height: 30px"
                    />
                    {% endif %}
                    <b style="margin-left: 45px">{{comment.author}}</b>
                    <div style="margin-left: 45px">{{comment.content}}</div>
                </div>
                <br />
            </div>
            {% empty %}
            <b style="color: #ff552b; text-align: center"
                >가장 먼저 댓글을 작성해보세요!
            </b>
            {% endfor %} 
            {% if user.is_authenticated %}
            <form style="text-align: right;" action="{% url 'lives:live_likes' video.pk %}" method="POST">
                {% csrf_token %} 
                {% if user in video.saves.all %}
                <button type="submit" id="bm_btn">저장안함</button>
                {% else %}
                <button type="submit" id="bm_btn">저장</button>
                {% endif %}
            </form>
            <form method="post">
                {% csrf_token %}
                <div style="display: flex; align-items:center; justify-content: space-around; padding: 10px">
                    {{form.as_p}}
                    <button type="submit" class="submitbox"><b>완료</b></button>
                </div>
            </form>
            {% else %}
             <b>로그인을 하세요</b> 
            {% endif %}
        </div>
    </body>
</html>

local/lives/templates/lives/live_home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/live.css' %}" />
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <style>
            a{
            text-decoration: none;
            color:black
            }
            .logout{
                position:absolute;
                top:23px;
                right:10px;
            }
            
                    </style>
    </head>
    <body>
        <div class="top">
            <img src="{% static 'logo.svg' %}" />
            {% if user.is_authenticated %}
            <div style="float: right; height: 30px">
                <img src="{% static 'alert.svg' %}" />
                <img
                    src="{% static 'ticket.svg' %}"
                    style="margin-right: 20px"
                />
                <b class="logout" style="color: #ff552b">3개</b>
            </div>
            {% endif %}
            <b
                style="
                    float: right;
                    text-decoration: underline;
                    color: gray;
                    font-size: 7pt;
                "
            >
                {% if user.is_authenticated %}

                <a href="{% url 'users:logout' %}">로그아웃</a>
                {% else %}
                <a href="{% url 'users:login' %}">로그인</a>
                {% endif %}
            </b>
        </div>
        <div>
            <ul class="menu1">
                <li>
                    <b><a href="{% url 'lives:live_list' %}">홈</a></b>
                </li>
                <li><a href="{% url 'lives:live_recent' %}">최신 방송순</a></li>
                <li><a href="{% url 'lives:live_soon' %}">라이브 예고</a></li>
            </ul>
        </div>
        <p>지금 <b style="color: #ff552b;">오사카</b>는?</p>
        <div class="container">
            {% if osaka1 %}
            <a href="{% url 'lives:live_detail' osaka1.pk %}">
                <img src="{{osaka1.thumbnail.url}}" class="left" style="width: 220px; height: 380px"/>
                <p>{{osaka1.state}}</p>
                <p>{{osaka1.title}}</p>
            </a>
            {% else %}
            <img src="" class="left" style="width: 220px; height: 380px"/>
            {% endif %}
            <div class="highlight">
                {% for osaka in osakas %}
                    <a href="{% url 'lives:live_detail' osaka.pk %}"><img src="{{osaka.thumbnail.url}}" class="box1" style="width: 100px; height: 120px"/></a>
                {% empty %}
                
                    <img src="" alt="없음" class="box1" style="width: 100px; height: 120px" />
                
                
                    <img src="" alt="없음" class="box1" style="width: 100px; height: 120px"/>
                
                
                    <img src="" alt="없음" class="box1" style="width: 100px; height: 120px"/>
                </div>
                {% endfor %}
            </div>
        </div>
        <b>오늘의 Live</b>
        <div>
            <ul class="today">
                <li class="box2">채팅 많은</li>
                <li class="box2">좋아요 폭발</li>
                <li class="box2">조회수 급상승</li>
            </ul>
        </div>
        <div class="container2">
            {% for video in video %}
            <div class="live_item">
                <img src="{{video.thumbnail.url}}" />
            </div>
            {% empty %} {% endfor %}
        </div>
        <footer>
            <div class="footer">
                <ul class="foot">
                    <li>
                        <a href="{% url 'lives:live_list' %}"
                            ><img src="{% static 'Group 4on.svg' %}"
                        /></a>
                    </li>
                    <li>
                        <a href="{% url 'dispatch:all_list' %}"><img src="{% static 'Group 3.svg' %}" /></a>
                    </li>
                    <li>
                        <a href="{% url 'travels:travel_list' %}"><img src="{% static 'Group 2.svg' %}" /></a>
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                        <a href="{% url 'users:mypage' %}">
                            <img src="{% static 'img/Group 511.svg' %}" />
                        </a>
                        {% else %}
                        <a href="{% url 'users:login' %}">
                            <img src="{% static 'img/Group 511.svg' %}" />
                        </a>
                        {% endif %}</li>
                </ul>
            </div>
        </footer>
    </body>
</html>

local/lives/templates/lives/live_recent.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <link rel="stylesheet" href="{% static 'css/recent.css' %}" />
        <link rel="stylesheet" href="{% static 'css/base.css' %}" />
        <style>
            a {
                text-decoration: none;
                color: black;
            }
            .logout {
                position: absolute;
                top: 23px;
                right: 10px;
            }
        </style>
    </head>
    <body>
        <div class="top">
            <img src="{% static 'logo.svg' %}" />
            {% if user.is_authenticated %}
            <div style="float: right; height: 30px">
                <img src="{% static 'alert.svg' %}" />
                <img
                    src="{% static 'ticket.svg' %}"
                    style="margin-right: 20px"
                />
                <b class="logout" style="color: #ff552b">3개</b>
            </div>
            {% endif %}
            <b
                style="
                    float: right;
                    text-decoration: underline;
                    color: gray;
                    font-size: 7pt;
                "
            >
                {% if user.is_authenticated %}

                <a href="{% url 'users:logout' %}">로그아웃</a>
                {% else %}
                <a href="{% url 'users:login' %}">로그인</a>
                {% endif %}
            </b>
        </div>
        <div>
            <ul class="menu1">
                <li>
                    <a href="{% url 'lives:live_list' %}">홈</a>
                </li>
                <li>
                    <a href="{% url 'lives:live_recent' %}"
                        ><b>최신 방송순</b></a
                    >
                </li>
                <li><a href="{% url 'lives:live_soon' %}">라이브 예고</a></li>
            </ul>
        </div>
        {% if query %}
        <p><b>"{{query}}" 에 대한 결과</b></p>
        {% else %}
        <p><b>최신 Live</b></p>
        {% endif %}
        <form id="rc-form" action="{% url 'lives:live_recent' %}">
            <input
                type="text"
                name="query"
                placeholder="현재 상황이 궁금한 여행지를 검색해보세요!"
                style="width: 80%"
            />
            <input type="submit" value="&#128269;" />
        </form>
        {% for video in video %}
        <a
            href="{% url 'lives:live_detail' video.pk %}"
            style="padding: 0; text-decoration: none"
        >
            <div class="box3">
                <img src="{{video.thumbnail.url}}" class="thumb" />
                <section class="vid">
                    <b>{{video.title}}</b>
                    <br /><b style="font-size: 10pt; color: #ff552b"
                        >{{video.nation}}, {{video.city}}</b
                    ><br />
                    <b>{{video.author.profile.nickname}}</b> <br />조회수
                    {{video.views}}
                </section>
            </div>
        </a>
        <br />
        {% empty %} {% endfor %}
        <footer>
            <div class="footer">
                <ul class="foot">
                    <li>
                        <a href="{% url 'lives:live_list' %}"
                            ><img src="{% static 'Group 4on.svg' %}"
                        /></a>
                    </li>
                    <li>
                        <a href="{% url 'dispatch:all_list' %}"><img src="{% static 'Group 3.svg' %}" /></a>
                    </li>
                    <li>
                        <a href="{% url 'travels:travel_list' %}"><img src="{% static 'Group 2.svg' %}" /></a>
                    </li>
                    <li>
                        {% if user.is_authenticated %}
                        <a href="{% url 'users:mypage' %}">
                            <img src="{% static 'Group 511.svg' %}" />
                        </a>
                        {% else %}
                        <a href="{% url 'users:login' %}">
                            <img src="{% static 'Group 511.svg' %}" />
                        </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </footer>
    </body>
</html>

local/lives/templates/lives/live_stream.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
    </head>
    <body>
        <img src="{% url 'lives:live_stream' %}" alt="Live Stream" />
        <button>Live 시작하기</button>
    </body>
</html>