local/dispatch/urls.py
from django.urls import path
from . import views
from .views import *

app_name = "dispatch"

urlpatterns = [
    # path('', views.whole_list, name='whole_list'),
    path('', views.whole_list, name='all_list'),
    path('near_list', views.near_list, name='near_list'),
    path('my_list', views.my_list, name='my_list'),
    path('post/', views.dispatch_post, name='dispatch_post'),
    path('<int:pk>/', views.dispatch_detail, name="dispatch_detail"),

    # path('<int:pk>/comment/', views.comments_create, name='comments_create'),

]

local/lives/urls.py
from django.urls import path
from .views import *


app_name = "lives"

urlpatterns = [
  path('cam/', live_stream, name='live_stream'),
  path('create/', live_create, name='live_create'),
  path('', live_list, name='live_list'),
  path('recent/', live_recent, name='live_recent'),
  path('soon/', live_soon, name='live_soon'),
  path("likes/<int:pk>/", live_likes, name='live_likes'),
  path('detail/<int:pk>', live_detail, name='live_detail'),
]

local/local/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('lives/', include('lives.urls')),
    path('accounts/', include('allauth.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('travels/', include('travels.urls')),
    path('dispatch/', include('dispatch.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

local/travels/urls.py
from django.urls import path
from .views import *

app_name = "travels"

urlpatterns = [
  path('', travel_list, name='travel_list'),
  path('<int:pk>/', travel_detail, name='travel_detail'),
  path("likes/<int:pk>/", travel_likes, name='travel_likes'),
  path('create/', travel_create, name='travel_creaet'),
  # path('delete/<int:pk>/', travel_delete, name='travel_delete'),
]

local/users/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views

app_name = "users"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signup/more-info', views.input_info, name='more_info'),
    path('login/', views.login, name='login'),
    path('id-login', views.id_login, name='id_login' ),
    path('logout/', views.logout, name='logout'),
    path('user/', views.user_view, name='user_list'),
    path('user/follow/<int:id>/<int:pk>/', views.user_follow, name='user_follow'),
    path('mypage/', views.mypage, name='mypage'),
]

local/users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User

class Profile(models.Model) :
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_provider = models.BooleanField(default=False)
    profile_photo = models.ImageField(blank=True, null=True, upload_to='profile_photo/')

    name = models.CharField(max_length=16, blank=False, default='')
    nickname = models.CharField(max_length=64, unique=True, blank=False, default='')
    phone = models.CharField(max_length=32, blank=False, default='')
    ticket_num = models.PositiveIntegerField(default=3)

    cntry_residence = models.CharField(max_length=32, blank=False, default='')
    city_residence = models.CharField(max_length=32, blank=False, default='')

    visited_cntry = models.CharField(max_length=64, blank=False, default='')
    visited_city = models.CharField(max_length=64, blank=False, default='')

    preferred_cntry = models.CharField(max_length=64, blank=False, default='')
    preferred_city = models.CharField(max_length=64, blank=False, default='')

    followers = models.ManyToManyField(User, related_name='followers')
    followings = models.ManyToManyField(User, related_name='followings')

    def __str__(self): 
        return self.nickname

local/users/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from users.models import Profile
from travels.models import TravelPost
from lives.models import Video


def signup(request):
    if request.method == "POST":
        if request.POST['password'] == request.POST['repeat']:
            new_user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'])
            auth.login(request, new_user, backend='django.contrib.auth.backends.ModelBackend')
            print('회원가입 성공')
            return redirect('users:more_info')
    return render(request, 'idsignup.html')

def input_info(request):
    if request.method == "POST":
        new_user = request.user
        name = request.POST['name'] 
        nickname = request.POST['nickname'] 
        phone = request.POST['phone'] 
        cntry_residence = request.POST['cntry_residence'] 
        city_residence = request.POST['city_residence'] 
        visited_cntry = request.POST['visited_cntry'] 
        visited_city = request.POST['visited_city'] 
        preferred_cntry = request.POST['preferred_cntry'] 
        preferred_city = request.POST['preferred_city'] 
        shop_option = request.POST['shop']

        try:
            profile = new_user.profile  # 기존에 연결된 프로필 객체 가져오기
            # 이미 연결된 프로필이 있는 경우 필드 업데이트
            profile.name = name
            profile.nickname = nickname
            profile.phone = phone
            profile.cntry_residence = cntry_residence
            profile.city_residence = city_residence
            profile.visited_cntry = visited_cntry
            profile.visited_city = visited_city
            profile.preferred_cntry = preferred_cntry
            profile.preferred_city = preferred_city
            if shop_option == 'No':
                profile.is_provider = False
            else:
                profile.is_provider = True
            profile.save()
        except Profile.DoesNotExist:
            # 연결된 프로필이 없는 경우 새로운 프로필 생성
            profile = Profile.objects.create(user=new_user, name=name, nickname=nickname, phone=phone,
                                             cntry_residence=cntry_residence, city_residence=city_residence,
                                             visited_cntry=visited_cntry, visited_city=visited_city,
                                             preferred_cntry=preferred_cntry, preferred_city=preferred_city,
                                             is_provider = (shop_option == 'Yes'))
        return redirect('lives:live_list')
    else:
        return render(request, 'general-signup.html')
    

def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)
            print('로그인 성공')
            return redirect('lives:live_list')
        else: 
            return render(request, 'bad_login.html')
    else:
        return render(request, 'onboarding.html')
    
def id_login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = auth.authenticate(request, username=username, password=password)

        if user is not None:
            auth.login(request, user)
            print('로그인 성공')
            return redirect('lives:live_list')
        else: 
            return render(request, 'bad_login.html')
    else:
        return render(request, 'phone_login.html')


def logout(request):
    auth.logout(request)
    return redirect('lives:live_list')


# 전체 사용자 리스트를 가져와서 user_list로 출력
@login_required
def user_view(request):
    if request.method == 'GET':
        user_list = Profile.objects.exclude(user=request.user).prefetch_related('followers', 'followings')
        return render(request, 'user_list.html', {'user_list':user_list, 'current_user': request.user})
    

def user_follow(request, id, pk):
    me = request.user
    click_user = User.objects.get(id=id)

    try:
        click_profile = Profile.objects.get(user=click_user)
    except Profile.DoesNotExist:
        # Profile 객체가 존재하지 않을 경우, 생성해야 함
        click_profile = Profile.objects.create(user=click_user)

    try:
        my_profile = Profile.objects.get(user=me)
    except Profile.DoesNotExist:
        # Profile 객체가 존재하지 않을 경우, 생성해야 함
        my_profile = Profile.objects.create(user=me)

    if my_profile.user in click_profile.followers.all():
        click_profile.followers.remove(my_profile.user)
        my_profile.followings.remove(click_user)
    else:
        click_profile.followers.add(my_profile.user)
        my_profile.followings.add(click_user)
    return redirect('travels:travel_detail', pk=pk)


@login_required
def mypage(request):
    if request.method == 'POST':
        mypage_list = request.POST.get('mypage-list')
        if mypage_list == "travel":
            objs = TravelPost.objects.filter(likes=request.user)
            travel = '여행리스트'
            context = {
                'travel': travel,
                'objs': objs,
            }
            return render(request, 'mypage.html', context)   
    objs = Video.objects.filter(saves=request.user)
    return render(request, 'mypage.html', {'objs': objs})

local/users/templates/bad_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>bad_login</title>
</head>
<body>
    존재하지 않는 회원입니다. 다시 로그인해주세요.
    <br/>
    <a href="{% url 'users:login' %}">다시 로그인하기</a>
</body>
</html>

local/users/templates/creater-signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/css/creater-signup.css"/>
    <title>Local</title>
</head>
<body>
    <div class="top-bar">
        <button type="button" id="close-button" onclick="location.href='onboarding.html'"><img src="../../static/img/close-button.png" alt="닫기"></button>
        <span id="txt-signup">추가 정보</span>
    </div>
    <div id="creater">
        <img src="../../static/img/logo.png" id="logo"><span id="txt">에서 라이브를 진행하거나 포스트를 발행하는</span><br>
        <span id="highlights">크리에이터 </span><span id="txt">활동을 하길 희망하시나요?</span>
        <div class="iscreater-btn">
        <button type="button" id="no-creater" onclick="location.href='general-signup.html'">
            <div id="no-txt">No</div>
            <div id="general-txt">일반회원</div>
        </button>
        <button type="button" id="yes-creater" onclick="location.href='creater-signup.html'">
            <div id="yes-txt">Yes</div>
            <div id="creater-txt">크리에이터</div></button><br/>
        </div>
        <div id="sub-txt">*크리에이터 회원으로 가입을 신청하시게 되면,<br/>
            추후 지역 인증과 별도의 심사를 통해 활동 권한을 얻을 수 있습니다.</div>
        <div id="sub-txt">자세한 문의는 고객센터를 통해 문의해 주십시오.</div>
    </div>
    <hr>
    <div class="input-box">
        <form id = "signup-form">
            <div id="box">
                <div id="txt">이름</span><span id="highlights"></div>
                <input type="text" placeholder="본인의 이름을 입력해 주세요." id="name">
            </div>
            <div id="box">
                <div id="txt">휴대폰</span><span id="highlights"></div>
                <input type="text" placeholder="‘-’ 제외하고 번호만 입력해 주세요." id="phone">
            </div>
            <div id="box">
                <div id="txt">닉네임</span><span id="highlights"></div>
                <input type="text" placeholder="로컬에서 사용할 닉네임을 입력해 주세요." id="nickname">
            </div>
            <div id="box">
                <div id="txt">거주 중인 국가</span><span id="highlights"></div>  
                <input type="text" placeholder="거주 중인 국가를 작성해주세요." id="living-country">
                <br><div id="sub-txt">예 : 대한민국, 일본, 태국, 미국, 대만</div>
            </div>  
            <div id="box">
                <div id="txt">거주 중인 도시</span><span id="highlights"></div>
                <input type="text" placeholder="거주 중인 국가를 작성해주세요." id="living-country">
                <br><div id="sub-txt-line">예 : 서울, 강릉, 제주, 나고야, 삿포로, 하노이, 파리, 로마, 뉴욕, 라스베가스</div>
            </div>
            <hr>
            <div id="box">
                <div id="txt">자주 방문하는 국가</span></div>
                <input type="text" placeholder="자주 방문하는 국가명을 입력해 주세요." id="visiting-country">
                <br><div id="sub-txt">예 : 대한민국, 일본, 태국, 미국, 대만</div>
            </div>
            <div id="box">
                <div id="txt">자주 방문하는 도시</span></div>
                <input type="text" placeholder="자주 방문하는 도시명을 입력해 주세요." id="visiting-city">
                <br><div id="sub-txt-line">예 : 서울, 강릉, 제주, 나고야, 삿포로, 하노이, 파리, 로마, 뉴욕, 라스베가스</div>
            </div>
            <hr>
            <div id="box">
                <div id="txt">여행하고 싶은 국가</span></div>
                <input type="text" placeholder="여행하고 싶은 국가명을 입력해 주세요." id="want-country">
                <br><div id="sub-txt">예 : 대한민국, 일본, 태국, 미국, 대만</div>
            </div>
            <div id="box-last">
                <div id="txt">여행하고 싶은 도시</div>
                <input type="text" placeholder="여행하고 싶은 도시명을 입력해 주세요." id="want-city">
                <br><div id="sub-txt">예 : 서울, 강릉, 제주, 나고야, 삿포로, 하노이, 파리, 로마, 뉴욕, 라스베가스</div>
            </div>
        </form>
    </div>
    <div id="start-box">
        <button type="button" onclick="location.href=''" id="next">로컬 시작하기!</button>
    </div>
</body>
</html>

local/users/templates/extra_info.html
<body>
    <h1>기타 정보 입력</h1>
    <form  method="POST">
        {% csrf_token %}
        <div>
            이름 : <input type="text" name="name" placeholder="이름 입력">
            닉네임 : <input type="text" name="nickname" placeholder="닉네임 입력">
            전화번호 : <input type="text" name="phone" placeholder="전화번호 입력">
        </div>
        <div>
            거주 중인 국가 : <input type="text" name="cntry_residence" placeholder="거주 중인 국가 입력">
            거주 중인 도시 : <input type="text" name="city_residence" placeholder="거주 중인 도시 입력">
        </div>
        <div>  <!-- 추가된 부분 -->
            자주 방문하는 국가 : <input type="text" name="visited_cntry" placeholder="자주 방문하는 국가 입력">
            자주 방문하는 도시 : <input type="text" name="visited_city" placeholder="자주 방문하는 도시 입력">
        </div>
        <div>
            가고 싶은 국가 : <input type="text" name="preferred_cntry" placeholder="가고 싶은 국가 입력">
            가고 싶은 도시 : <input type="text" name="preferred_city" placeholder="가고 싶은 도시 입력">
        </div>
        <br><hr>
        <input type="submit" value="로컬 시작하기">
    </form>
</body>

local/users/templates/general-signup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/general-signup.css' %}"/>
    <title>Local</title>
</head>
<body>
    <div class="top-bar">
        <button type="button" id="close-button" onclick="href='/mypage'"><img src="{% static 'img/close-button.png' %}" alt="닫기"></button>
        <span id="txt-signup">추가정보</span>
    </div>
    <form method="POST">
        {% csrf_token %}

        <div id="creater">
            <img src="{% static 'img/logo.png' %}" id="logo"><span id="txt">에서 라이브를 진행하거나 포스트를 발행하는</span><br>
            <span id="highlights">크리에이터 </span><span id="txt">활동을 하길 희망하시나요?</span>
            <div class="select">
                <input type="radio" id="select" name="shop" value="No"><label for="select">No</label>
                <input type="radio" id="select2" name="shop" value="Yes"><label for="select2">Yes</label>
           </div>

            <div id="sub-txt">*크리에이터 회원으로 가입을 신청하시게 되면,<br/>
                추후 지역 인증과 별도의 심사를 통해 활동 권한을 얻을 수 있습니다.</div>
            <div id="sub-txt">자세한 문의는 고객센터를 통해 문의해 주십시오.</div>
        </div>
        <hr>
        <div class="input-box">
            <div id = "signup-form">
                <div id="box">
                    <div id="txt">이름</span><span id="highlights"></div>
                    <input type="text" name="name" placeholder="본인의 이름을 입력해 주세요." id="name">
                </div>
                <div id="box">
                    <div id="txt">휴대폰</span><span id="highlights"></div>
                    <input type="text" name="phone" placeholder="‘-’ 제외하고 번호만 입력해 주세요." id="phone">
                </div>
                <div id="box">
                    <div id="txt">닉네임</span><span id="highlights"></div>
                    <input type="text" name="nickname" placeholder="로컬에서 사용할 닉네임을 입력해 주세요." id="nickname">
                </div>
                <div id="box">
                    <div id="txt">거주 중인 국가</span><span id="highlights"></div>  
                    <input type="text" name="cntry_residence" placeholder="거주 중인 국가를 작성해주세요." id="living-country">
                    <br><div id="sub-txt">예 : 대한민국, 일본, 태국, 미국, 대만</div>
                </div>  
                <div id="box">
                    <div id="txt">거주 중인 도시</span><span id="highlights"></div>
                    <input type="text" name="city_residence" placeholder="거주 중인 국가를 작성해주세요." id="living-country">
                    <br><div id="sub-txt-line">예 : 서울, 강릉, 제주, 나고야, 삿포로, 하노이, 파리, 로마, 뉴욕, 라스베가스</div>
                </div>
                <hr>
                <div id="box">
                    <div id="txt">자주 방문하는 국가</span></div>
                    <input type="text" name="visited_cntry" placeholder="자주 방문하는 국가명을 입력해 주세요." id="visiting-country">
                    <br><div id="sub-txt">예 : 대한민국, 일본, 태국, 미국, 대만</div>
                </div>
                <div id="box">
                    <div id="txt">자주 방문하는 도시</span></div>
                    <input type="text" name="visited_city" placeholder="자주 방문하는 도시명을 입력해 주세요." id="visiting-city">
                    <br><div id="sub-txt-line">예 : 서울, 강릉, 제주, 나고야, 삿포로, 하노이, 파리, 로마, 뉴욕, 라스베가스</div>
                </div>
                <hr>
                <div id="box">
                    <div id="txt">여행하고 싶은 국가</span></div>
                    <input type="text" name="preferred_cntry" placeholder="여행하고 싶은 국가명을 입력해 주세요." id="want-country">
                    <br><div id="sub-txt">예 : 대한민국, 일본, 태국, 미국, 대만</div>
                </div>
                <div id="box">
                    <div id="txt">여행하고 싶은 도시</div>
                    <input type="text" name="preferred_city" placeholder="여행하고 싶은 도시명을 입력해 주세요." id="want-city">
                    <br><div id="sub-txt">예 : 서울, 강릉, 제주, 나고야, 삿포로, 하노이, 파리, 로마, 뉴욕, 라스베가스</div>
                </div>
                <div id="box-last">
                    <div id="txt">프로필 사진</div>
                    <input type="file" name="profile">
                </div>
            </form>
        </div>
        <div id="start-box">
            <button type="submit" id="next">로컬 시작하기!</button>
        </div>


    </form>

</body>
</html>

local/users/templates/idsignup.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/idsignup.css' %}"/>
    <title>Local</title>
</head>
<body>
    <div class="top-bar">
        <button type="button" id="close-button" onclick="location.href='onboarding.html'"><img src="{% static 'img/close-button.png' %}" alt="닫기"></button>
        <span id="txt-signup">아이디로 회원가입</span>
    </div>

    <form class="user" method="POST">
        {% csrf_token %}
        <div class="id-input">
            <span id="txt">아이디</span><span id="highlights">*</span>
            <div id = "id-form">
                <input required maxlength="15" type="text" name="username" placeholder="예: local230714" id="id">
            </div>
            <span id="sub-txt">영문과 숫자를 조합하여 6자 이상</span>
        </div>
        <div class="pw-input">
            <span id="txt">비밀번호</span><span id="highlights">*</span>
            <div id = "pw-form">
                <input required maxlength="15" type="password" name="password" placeholder="비밀번호를 입력해주세요." id="pw1">
            </div>
            <span id="sub-txt">영문,숫자,특수문자 중 2개 이상 조합하여 10자 이상</span>
        </div>
        <div class="pw-confirm">
            <span id="txt">비밀번호 확인</span><span id="highlights">*</span>
            <div id = "pw-form">
                <input required maxlength="15" type="password" name="repeat" placeholder="위에서 입력한 비밀번호를 한 번 더 입력해주세요." id="pw2">
            </div>
            <span id="sub-txt">영문,숫자,특수문자 중 2개 이상 조합하여 10자 이상</span>
        </div>
        <button type="submit" id="next">다음</button>
        <!-- <a href="{% url 'users:more_info' %}"></a> -->
    </form>


</body>
</html>

local/users/templates/login.html
{% load socialaccount %}

<a href="{% url 'users:signup' %}">일반 회원가입</a>
<a href="{% url 'users:logout' %}">내가 구현한 로그아웃</a>

<form method="POST" class="joinForm">
    {% csrf_token %}
    <h1>LOGIN</h1>

    <h2>일반 로그인</h2>
    <form class="user" method="POST">
        {% csrf_token %}
        <div>
            <input type="text" id="username" name="username" placeholder="아이디를 입력해주세요.">
        </div>
        <div>
            <input type="password" id="password" name="password" placeholder="비밀번호를 입력해주세요.">
        </div>
        <input type="submit" value="로그인">
        <hr>
    </form>

    <h2>카카오 로그인</h2>
    <div>
        <a href="{% provider_login_url 'kakao' %}">
            <i>카카오 로그인</i>
        </a>
    </div>

</form>

local/users/templates/mypage.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/mypage.css' %}">
  <title>Local</title>
</head>
<body>
  <div id="mpage-main">
    <div id="logo-bar" class="p-1">
      <img src="{% static 'img/logo.svg' %}" alt="">
      <div class="flex align-center">
        <a href=""><img src="{% static 'img/alert.svg' %}" alt=""></a>
        {% if user.is_authenticated %}
        <p class="flex align-center"><img src="{% static 'img/ticket.svg' %}" alt="">{{request.user.profile.ticket_num}}개</p>
        {% endif %}
      </div>
    </div>
    <nav id="mpage-nav" class="p-1">
      <a href="" id="profile-btn">프로필</a>
    </nav>
    <img src="{% static 'img/bar.svg'%}" id="bar">
    <div id="my-box" class="flex align-center">
      <img id="mpage-img" src="{% static 'img/alert.svg' %}" alt="">
      <div class="p-rl">
        {% if request.user.profile.nickname %}
        <h3>{{request.user.profile.nickname}}</h3>
        {% else %}
        <h3>닉네임을 설정하세요.</h3>
        {% endif %}
        <p><span id="sub-txt">팔로워</span> <span id="bold">{{request.user.profile.followers.count}}</span> | <span id="sub-txt">팔로잉</span> <span id="bold">{{request.user.profile.followings.count}}</span></p>
        <p><span id="highlight">{{request.user.profile.city_residence}}</span> <span id="txt">리얼 로컬</span></p>
        <small><a href="{% url 'users:more_info' %}" id="txt-change">정보변경</a></small>
      </div>
    </div>
    <p class="p-1">북마크</p>

    <form method="POST" action="{% url 'users:mypage' %}">
      {% csrf_token %}
      <div class="flex" id="mpage-savebox">
        <button type="submit" name="mypage-list" value="live" id="live-btn">
          <p id="howmany">{{request.user.Livelikes.all.count}}</p>
          <p>라이브</p>
        </button>
        <button type="submit" name="mypage-list" value="travel" id="travel-btn">
          <p id="howmany">{{request.user.TravelLikes.all.count}}</p>
          <p>여행</p>
        </button>
      </div>
    </form>

    {% comment %} for 문 돌릴곳 {% endcomment %}
    {% for obj in objs %}
    <div class="flex save-list align-center">
      <img src="{% static 'img/ticket.svg' %}" alt="">
      <div>
        <h4>{{obj.title}}</h4>
        <p>{{obj.nation}}</p>
        <p>{{obj.author}}</p>
        <p>{{obj.views}}</p>
      </div>
    </div>
    {% endfor %}
    {% comment %} for문 끝 {% endcomment %} 

  <footer>
    <ul class="foot">
      <li>
        <a href="{% url 'lives:live_list' %}">
          <img src="{% static 'img/lolive.svg' %}"/>
        </a>
      </li>
      <li>
        <a href="{% url 'dispatch:all_list' %}"><img src="{% static 'Group 3.svg' %}" /></a>
      </li>
      <li>
        <a href="{% url 'travels:travel_list' %}"><img src="{% static 'Group 2.svg' %}" /></a>
      </li>
      <li>
        <a href="{% url 'users:mypage' %}">
          <img src="{% static 'img/mypa.svg' %}" />
        </a>
      </li>
    </ul>
  </footer>
</body>
</html>

local/users/templates/onboarding-fin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Local</title>
    <link rel="stylesheet" href="../../static/css/onboarding-fin.css"/>
</head>
<body>
    <div id="fin-message"><span id="highlights">닉네임</span> 님, 환영합니다!<br/>
    로컬을 사용할<br/>준비를 모두 마쳤어요.</div>
    <img src="../../static/img/logo.png">
    <button type="button" onclick="location.href=''" id="next">로컬 시작하기!</button>
</body>
</html>

local/users/templates/onboarding.html
{% load socialaccount %}
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/onboarding.css' %}"/>
    <title>Local</title>
</head>
<body>
    <div class="top-bar">
        <span id="txt-login">로그인</span>
    </div>
    <div id="start-message">
        생생한 <span id="highlights">현지</span> 여행 정보를<br/>
        지금 두 눈으로 보고, <br/>
        <span id="highlights">로컬</span>에게 물어보기.</div>
        <img id="logo" src="{% static 'img/logo.png' %}">
    <br/>
    <a href="{% provider_login_url 'kakao' %}"><button type="button" onclick="location.href='step3.html'" id="kakao-login">카카오로 시작하기</button></a>
    <a href="{% url 'users:id_login' %}"><button type="button" id="phone-login">아이디로 로그인하기</button></a>
    <div id="q">
        <span>로컬 계정이 없으신가요?</span> 
        <a href="#pop1" id="signup-btn" class="btn_open">회원가입</a>
    </div>
    <div id="pop1" class="pop_wrap" style="display:none;">
        <div class="pop_inner">
            <div id="top"><img src="{% static 'img/logo.png' %}" id="small-logo">
            <span id="signup-txt">회원가입</span>
            <a href="{% url 'users:login' %}"><button type="button" class="btn_close"><img src="{% static 'img/close-button.png' %}"></button></a></div>
            <br>
            <a href="{% provider_login_url 'kakao' %}"><button type="button" id="kakao-signup" onclick="location.href='nickname.html'">카카오로 시작하기</button></a>
            <a href="{% url 'users:signup' %}"><button type="button" id="id-signup" onclick="location.href='idsignup.html'">아이디로 회원가입</button></a>
        </div>
      </div>


    <div class="footer">
        <button type="button" id="live-btn"><img src="{% static 'img/live-button.png' %}"></button>
        <button type="button" id="dispatch-btn"><img src="{% static 'img/dispatch-button.png' %}"></button>
        <button type="button" id="travel-btn"><img src="{% static 'img/travel-button.png' %}"></button>
        <button type="button" id="mypage-btn"><img src="{% static 'img/mypage-button-check.png' %}"></button>
    </div>
    <script src ="{% static 'js/onboarding.js' %}"></script>
</body>
</html>